# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: Crystal's Adventures

# Below the site title
tagline: Weekend warrior

# Site logo
logo:

# A description of your site for social meta tag, search engines, and feed.xml
description: |
  BlogBox is a bold theme for the Jekyll blogging platform. Available for purchase at ThemeForest.net.

# The base hostname & protocol of your site for where absolute urls are needed
url: https://blogbox.netlify.app

# The subpath of your site, if you want to host your path on a subpath like on GitHub Pages. e.g. /blog
baseurl:

sass:
  sass_dir: _sass

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Style Guide
  url: /style-guide/
- text: Archives
  url: /tags/

# Author information - author info at the bottom of the post
author_name: "Crystal"
author_bio: "My name is Crystal. I like to run up and down things mostly on weekends. This blog is about my random adventures and things I've learned from it."
author_url: "https://justgoodthemes.com"
author_location: "Vilnius, Lithuania"
author_image: authorimage.jpg

# Footer ad banner
banner_image: banner.jpg
banner_url: https://justgoodthemes.com/

# Footer newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: ""

# Social links in the site footer
twitter_username: "username"
facebook_username: "username"
github_username: "username"
codepen_username: "username"
dribbble_username: "username"
medium_username: "@username"
instagram_username: "username"
pinterest_username: "username"
linkedin_username: "username"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
